### ISSUE TITLE
Diseño de campañas para referidos

### ISSUE THREAD

**Issue by pamsili** [VENMETRO/MarketingBoard#105]
2 DIseños de campañas para:

- Facebook e Instagram.
- Exportar listado de usuarios registrados como promotores de referidos.

**Comment by jeandesign01** [comment]
![pruebas-de-diseñoMesa-de-trabajo-1-copia-3.png](https://images.zenhubusercontent.com/5a5d17494b5806bc2bc2d545/dddd8d35-beae-4fd4-bf40-a0fd954f1a5b)

![Link-AD.png](https://images.zenhubusercontent.com/5a5d17494b5806bc2bc2d545/999a04b4-6174-4df5-b015-635a1f1cd28f)
