### ISSUE TITLE
Campaña de referidos

### ISSUE THREAD

**Issue by AlexandraChen** [VENMETRO/MarketingBoard#130]
- [x] Crear diseño de campaña
- [x] Activar los públicos
- [x] Antes de activar campaña, confirmar con tech team si está en producción

**Comment by pamsili** [comment]
![Link-AD](https://user-images.githubusercontent.com/56312282/74878040-22754a80-532c-11ea-93a4-af150f4fa77b.png)
![Uploading pruebas-de-diseñoMesa-de-trabajo-1-copia-3.png…]()

**Comment by pamsili** [comment]
![pruebas-de-diseñoMesa-de-trabajo-1-copia-3](https://user-images.githubusercontent.com/56312282/74878070-315bfd00-532c-11ea-9f62-51a25276fbee.png)
